# Generated by Django 3.1.7 on 2021-03-20 21:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=1000, null=True)),
                ('stars', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('website', models.URLField(max_length=5000, null=True)),
                ('images_url', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('description', models.CharField(max_length=50000, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('check_in', models.TimeField(null=True)),
                ('check_out', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='0')),
                ('price', models.CharField(max_length=100, null=True)),
                ('hotel_name', models.CharField(max_length=1000, null=True)),
                ('stars', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('website', models.URLField(max_length=5000, null=True)),
                ('images_url', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('description', models.CharField(max_length=50000, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('check_in', models.TimeField(null=True)),
                ('check_out', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='0')),
                ('price_per_pas', models.CharField(default='NONE', max_length=100)),
                ('booking_link', models.URLField(default='NONE', max_length=5000)),
                ('departure', models.CharField(default='NONE', max_length=5000)),
                ('arrival', models.CharField(default='NONE', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_adults', models.IntegerField(default=1)),
                ('no_of_children', models.IntegerField(default=0)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('budget', models.CharField(choices=[('low', 'Cheapest possible trip - maximise things to do'), ('intermediate', 'Comfortable trip'), ('high', 'Luxury trip - budget is not an issue')], default='intermediate', max_length=12)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_city', to='cities_light.city')),
                ('destination_city', models.ForeignKey(limit_choices_to={'id': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_city', to='cities_light.city')),
            ],
        ),
    ]
