# Generated by Django 3.1.7 on 2021-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accom_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='flight_id',
            field=models.IntegerField(default=0),
        ),
    ]
