# Generated by Django 3.1.7 on 2021-03-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.CharField(choices=[('low', 'Cheapest possible trip - maximise things to do'), ('intermediate', 'Comfortable trip'), ('high', 'Luxury trip - budget is not an issue')], default='intermediate', max_length=12),
        ),
    ]
