# Generated by Django 3.1.7 on 2021-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210322_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomdatabase',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='accominfo',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
