# Generated by Django 3.1.7 on 2021-03-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210322_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightinfo',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='flightinfo',
            name='departure',
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_arrival_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_carrier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_depart_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_layovers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_stop_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_arrival_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_carrier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_depart_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_layovers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_stop_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightinfo',
            name='booking_link',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='flightinfo',
            name='price_per_pas',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
