# Generated by Django 3.1.7 on 2021-03-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('search', '0003_auto_20210308_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departure_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country'),
        ),
    ]
