# Generated by Django 3.1.7 on 2021-03-28 20:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210326_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_arrival_airport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_depart_airport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='arrival_logo_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_arrival_airport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_depart_airport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='departure_logo_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None),
        ),
    ]
