# Generated by Django 3.1.7 on 2021-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210308_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='destination_city',
            field=models.CharField(choices=[('Singapore', 'Singapore')], default='Singapore', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='destination_country',
            field=models.CharField(choices=[('Singapore', 'Singapore')], default='Singapore', max_length=200),
        ),
    ]
