# Generated by Django 3.1.7 on 2021-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210308_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departure_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='destination_country',
        ),
        migrations.AlterField(
            model_name='user',
            name='destination_city',
            field=models.CharField(choices=[('Singapore', 'Singapore, Singapore')], default='Singapore', max_length=200),
        ),
    ]
