# Generated by Django 3.1.7 on 2021-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210310_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_of_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_of_children',
            field=models.IntegerField(default=1),
        ),
    ]
