# Generated by Django 3.1.7 on 2021-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20210310_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='destination_city',
            field=models.CharField(choices=[('Singapore, Singapore', 'Singapore, Singapore')], default='Singapore, Singapore', max_length=200),
        ),
    ]
