# Generated by Django 3.1.7 on 2021-03-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('search', '0009_auto_20210310_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure_city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='destination_city',
            field=models.ForeignKey(limit_choices_to={'id': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_city', to='cities_light.city'),
        ),
    ]
