# Generated by Django 3.1.7 on 2021-03-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20210310_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
