# Generated by Django 3.1.7 on 2021-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_flightinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightInfo',
        ),
    ]
